/**
 * Exam Management API
 * This API exposes endpoints to manage client.
 *
 * OpenAPI spec version: 1.0
 * Contact: yessinelleuch00@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompteDTO } from './compteDTO';

export interface CompteListDTO { 
    comptes?: Array<CompteDTO>;
    totalElements?: number;
    totalPages?: number;
}